# Generated by Django 5.2.6 on 2025-11-20 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending_review', '待审核'), ('pending_payment', '待付款'), ('scheduling', '排产中'), ('processing', '加工中'), ('quality_check', '质检中'), ('shipped', '已发货'), ('completed', '完成'), ('cancelled', '已取消')], default='pending_review', max_length=20, verbose_name='订单状态')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('product_description', models.TextField(blank=True, verbose_name='产品描述')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('promised_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='承诺交期')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='实际交期')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='客户邮箱')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='客户电话')),
                ('customer_company', models.CharField(blank=True, max_length=200, verbose_name='客户公司')),
                ('shipping_address', models.TextField(verbose_name='收货地址')),
                ('shipping_contact', models.CharField(max_length=100, verbose_name='收货联系人')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='收货电话')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_review', '待审核'), ('pending_payment', '待付款'), ('scheduling', '排产中'), ('processing', '加工中'), ('quality_check', '质检中'), ('shipped', '已发货'), ('completed', '完成'), ('cancelled', '已取消')], max_length=20, verbose_name='状态')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间戳')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='操作人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': '订单状态历史',
                'verbose_name_plural': '订单状态历史',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100, verbose_name='生产阶段')),
                ('description', models.TextField(verbose_name='描述')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('monitoring_image', models.ImageField(blank=True, null=True, upload_to='monitoring/', verbose_name='监控图片')),
                ('monitoring_description', models.CharField(blank=True, max_length=200, verbose_name='监控描述')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_progress', to='orders.order')),
            ],
            options={
                'verbose_name': '生产进度',
                'verbose_name_plural': '生产进度',
                'ordering': ['id'],
            },
        ),
    ]
