# Generated by Django 5.2.6 on 2025-11-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('quotation', '0009_quotationrequest_estimated_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quotation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.quotationrequest', verbose_name='报价请求'),
        ),
    ]
