# Generated by Django 5.2.8 on 2025-11-20 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'ordering': ['order', 'id'], 'verbose_name': '论坛版块', 'verbose_name_plural': '论坛版块'},
        ),
        migrations.RemoveField(
            model_name='forumcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='status',
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='slug',
            field=models.SlugField(default='', help_text='用于URL的唯一标识，只能包含字母、数字、连字符', unique=True, verbose_name='URL标识'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='已发布'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='版块名称'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='数值越小排序越靠前', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumcategory', verbose_name='所属版块'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.DeleteModel(
            name='ForumComment',
        ),
    ]
