# Generated by Django 5.2.8 on 2025-11-18 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作品分类',
                'verbose_name_plural': '作品分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品标题')),
                ('description', models.TextField(verbose_name='作品描述')),
                ('image', models.ImageField(blank=True, upload_to='works/images/', verbose_name='展示图片')),
                ('project_background', models.TextField(verbose_name='项目背景')),
                ('model_file', models.FileField(blank=True, upload_to='works/models/', verbose_name='3D模型文件')),
                ('process_difficulties', models.TextField(verbose_name='加工难点与解决方案')),
                ('equipment_used', models.TextField(verbose_name='使用设备')),
                ('materials', models.TextField(verbose_name='材料')),
                ('process_techniques', models.TextField(verbose_name='工艺')),
                ('project_duration', models.CharField(max_length=100, verbose_name='项目周期')),
                ('video_url', models.URLField(blank=True, verbose_name='视频链接')),
                ('is_featured', models.BooleanField(default=False, verbose_name='推荐作品')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'ordering': ['-created_at'],
            },
        ),
    ]
