# Generated by Django 5.2.8 on 2025-11-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_populate_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='URL标识'),
        ),
    ]
