# Generated by Django 5.2.8 on 2025-11-18 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('processing_type', models.CharField(choices=[('cnc_milling', 'CNC铣削'), ('cnc_turning', 'CNC车削'), ('3d_printing', '3D打印')], max_length=20, verbose_name='加工类型')),
                ('material', models.CharField(choices=[('aluminum', '铝合金'), ('steel', '钢材'), ('stainless_steel', '不锈钢'), ('plastic', '塑料'), ('other', '其他')], max_length=20, verbose_name='材料')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('accuracy', models.CharField(max_length=50, verbose_name='精度要求')),
                ('surface_treatment', models.CharField(choices=[('none', '无'), ('anodizing', '阳极氧化'), ('painting', '喷漆'), ('polishing', '抛光'), ('other', '其他')], max_length=20, verbose_name='表面处理')),
                ('description', models.TextField(blank=True, verbose_name='附加说明')),
                ('model_file', models.FileField(blank=True, upload_to='quotation_models/', verbose_name='3D模型文件')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_processed', models.BooleanField(default=False, verbose_name='已处理')),
            ],
            options={
                'verbose_name': '报价请求',
                'verbose_name_plural': '报价请求',
                'ordering': ['-created_at'],
            },
        ),
    ]
