# Generated by Django 5.2.8 on 2025-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='bounding_box_height',
            field=models.FloatField(blank=True, null=True, verbose_name='包围盒高度 (mm)'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='bounding_box_length',
            field=models.FloatField(blank=True, null=True, verbose_name='包围盒长度 (mm)'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='bounding_box_width',
            field=models.FloatField(blank=True, null=True, verbose_name='包围盒宽度 (mm)'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='complexity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='复杂度评分'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='max_aspect_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='最大径长比'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='min_radius',
            field=models.FloatField(blank=True, null=True, verbose_name='最小拐角半径 (mm)'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='surface_area',
            field=models.FloatField(blank=True, null=True, verbose_name='表面积 (cm²)'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='体积 (cm³)'),
        ),
    ]
