# Generated by Django 5.2.8 on 2025-11-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotationrequest_bounding_box_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='machining_difficulty',
            field=models.FloatField(blank=True, null=True, verbose_name='加工难度评分'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='min_tool_diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='最小刀具直径 (mm)'),
        ),
    ]
