# Generated by Django 5.2.6 on 2025-11-19 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotationrequest_machining_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationAdjustmentFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='因子名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('value', models.FloatField(default=1.0, verbose_name='因子值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报价调控因子',
                'verbose_name_plural': '报价调控因子',
                'ordering': ['name'],
            },
        ),
    ]
