# Generated by Django 5.2.6 on 2025-11-19 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotationadjustmentfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFMAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分析名称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='公司')),
                ('model_file', models.FileField(upload_to='dfm_models/', verbose_name='3D模型文件')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='体积 (cm³)')),
                ('surface_area', models.FloatField(blank=True, null=True, verbose_name='表面积 (cm²)')),
                ('bounding_box_length', models.FloatField(blank=True, null=True, verbose_name='包围盒长度 (mm)')),
                ('bounding_box_width', models.FloatField(blank=True, null=True, verbose_name='包围盒宽度 (mm)')),
                ('bounding_box_height', models.FloatField(blank=True, null=True, verbose_name='包围盒高度 (mm)')),
                ('min_radius', models.FloatField(blank=True, null=True, verbose_name='最小拐角半径 (mm)')),
                ('max_aspect_ratio', models.FloatField(blank=True, null=True, verbose_name='最大径长比')),
                ('complexity_score', models.FloatField(blank=True, null=True, verbose_name='复杂度评分')),
                ('min_tool_diameter', models.FloatField(blank=True, null=True, verbose_name='最小刀具直径 (mm)')),
                ('machining_difficulty', models.FloatField(blank=True, null=True, verbose_name='加工难度评分')),
                ('recommendations', models.TextField(blank=True, verbose_name='优化建议')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_processed', models.BooleanField(default=False, verbose_name='已处理')),
            ],
            options={
                'verbose_name': 'DFM分析',
                'verbose_name_plural': 'DFM分析',
                'ordering': ['-created_at'],
            },
        ),
    ]
