# Generated by Django 5.2.8 on 2025-11-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_dfmanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='curved_surfaces',
            field=models.IntegerField(blank=True, null=True, verbose_name='曲面数量'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='estimated_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='估算重量'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='holes',
            field=models.IntegerField(blank=True, null=True, verbose_name='孔洞数量'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='min_tolerance',
            field=models.FloatField(blank=True, null=True, verbose_name='最小公差要求'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='oc_machining_difficulty',
            field=models.CharField(blank=True, choices=[('EASY', '容易'), ('MEDIUM', '中等'), ('HARD', '困难'), ('VERY_HARD', '非常困难')], max_length=20, null=True, verbose_name='OpenCASCADE加工难度'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='sharp_edges',
            field=models.IntegerField(blank=True, null=True, verbose_name='锐边数量'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='undercuts',
            field=models.IntegerField(blank=True, null=True, verbose_name='倒勾特征数量'),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='surface_area',
            field=models.FloatField(blank=True, null=True, verbose_name='表面积'),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='体积'),
        ),
    ]
