# Generated by Django 5.2.8 on 2025-11-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_quotationrequest_curved_surfaces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_cnc_difficulty_level',
            field=models.CharField(blank=True, choices=[('EASY', '容易'), ('MEDIUM', '中等'), ('HARD', '困难')], max_length=20, null=True, verbose_name='CNC难度等级'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_cnc_difficulty_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='CNC难度评分'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_estimated_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='估算成本'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_fillets',
            field=models.IntegerField(blank=True, null=True, verbose_name='圆角数量'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_finishing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='精加工时间(分钟)'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_holes',
            field=models.IntegerField(blank=True, null=True, verbose_name='孔数量'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_recommended_process',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='推荐工艺'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_roughing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='粗加工时间(分钟)'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_thin_walls',
            field=models.BooleanField(default=False, verbose_name='薄壁结构'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_utilization_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='材料利用率(%)'),
        ),
        migrations.AddField(
            model_name='dfmanalysis',
            name='cq_waste_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='材料浪费量'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_cnc_difficulty_level',
            field=models.CharField(blank=True, choices=[('EASY', '容易'), ('MEDIUM', '中等'), ('HARD', '困难')], max_length=20, null=True, verbose_name='CNC难度等级'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_cnc_difficulty_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='CNC难度评分'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_estimated_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='估算成本'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_fillets',
            field=models.IntegerField(blank=True, null=True, verbose_name='圆角数量'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_finishing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='精加工时间(分钟)'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_holes',
            field=models.IntegerField(blank=True, null=True, verbose_name='孔数量'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_recommended_process',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='推荐工艺'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_roughing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='粗加工时间(分钟)'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_thin_walls',
            field=models.BooleanField(default=False, verbose_name='薄壁结构'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_utilization_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='材料利用率(%)'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='cq_waste_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='材料浪费量'),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='surface_area',
            field=models.FloatField(blank=True, null=True, verbose_name='表面积 (cm²)'),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='体积 (cm³)'),
        ),
    ]
