# Generated by Django 5.2.6 on 2025-11-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_dfmanalysis_cq_cnc_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationrequest',
            old_name='curved_surfaces',
            new_name='oc_curved_surfaces',
        ),
        migrations.RenameField(
            model_name='quotationrequest',
            old_name='estimated_weight',
            new_name='oc_estimated_weight',
        ),
        migrations.RenameField(
            model_name='quotationrequest',
            old_name='holes',
            new_name='oc_holes',
        ),
        migrations.RenameField(
            model_name='quotationrequest',
            old_name='min_tolerance',
            new_name='oc_min_tolerance',
        ),
        migrations.RenameField(
            model_name='quotationrequest',
            old_name='sharp_edges',
            new_name='oc_sharp_edges',
        ),
        migrations.RenameField(
            model_name='quotationrequest',
            old_name='undercuts',
            new_name='oc_undercuts',
        ),
    ]
