# Generated by Django 5.2.6 on 2025-11-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_rename_curved_surfaces_quotationrequest_oc_curved_surfaces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估价格'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最终价格'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='price_explanation',
            field=models.TextField(blank=True, verbose_name='价格说明'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('quoted', '已报价'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='报价状态'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
