# Generated by Django 5.2.6 on 2025-11-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_quotationrequest_estimated_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='part_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='零件名称'),
        ),
    ]
