# Generated by Django 5.2.6 on 2025-11-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_quotationrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='联系人'),
        ),
    ]
