# Generated by Django 5.2.8 on 2025-11-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_quotationrequest_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='dmf_complexity_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='复杂度因子'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='dmf_feature_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='特征因子'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='dmf_precision_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='精度因子'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='dmf_surface_area_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='表面积因子'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='dmf_volume_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='体积因子'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='材料费用'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='other_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='其他费用'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='packaging_shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='包装物流费用'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='processing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='加工费用'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='programming_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='编程费用'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='surface_treatment_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='表面处理费用'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='tax_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='税费'),
        ),
    ]
