# Generated by Django 2.2.2 on 2025-11-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_quotationrequest_dmf_complexity_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='利润金额', max_digits=10, null=True, verbose_name='利润金额'),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='利润率百分比', max_digits=5, null=True, verbose_name='利润率(%)'),
        ),
        migrations.AlterField(
            model_name='dfmanalysis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quotationadjustmentfactor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
