# Generated by Django 2.2.2 on 2025-11-27 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0014_auto_20251127_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfmanalysis',
            name='user',
            field=models.ForeignKey(blank=True, help_text='上传分析的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
